### ISSUE TITLE
Extraneous Input Boxes

### ISSUE THREAD

**Issue by estasney** [CiscoTalentHub/TalentHub#3]
On https://ciscotalenthub.github.io/TalentHub/index_typeahead_multi.html:

Two extraneous input fields are showing:
```
#typeaheadmulti_company > ul
#typeaheadmulti > ul

```

**Comment by CiscoTalentHub** [comment]
The extraneous input fields are used by the plugin to store the list of selected items.  So it overlaps.

I’m having issues with styling the input fields .company and .titles because there is a bug with it taking a percentage for the width.  Currently using a fixed px width for now, but doesn’t scale properly.   Oddly the extraneous input fields don’t have the same problem.  They are wrapped around the same div.  Somehow the width is over ridden by another element.  

Will continue to debug.

Thanks,

DH

**Comment by CiscoTalentHub** [comment]
Found that .twitter-typeahead conflicts with the styling.  Added the below CSS to overide and it scales fine now.

.twitter-typeahead {
  width: 98.5% !important;
}

DH
